<?php

if ( function_exists("register_field_group") )
{
	if ( ! ($tier1 = get_option('options_location_tier_1')) ) {
        $tier1 = 'Building';
    }
    if ( ! ($tier2 = get_option('options_location_tier_2')) ) {
        $tier2 = 'Floor';
    }
    if ( ! ($tier3 = get_option('options_location_tier_3')) ) {
        $tier3 = 'Subarea';
    }

	register_field_group(array (
		'id' => 'acf_rfis',
		'title' => 'RFIs',
		'fields' => array (
			array (
				'key' => 'field_53c680f0a9978',
				'label' => 'Tracking',
				'name' => '',
				'type' => 'message',
				'message' => '<h2>Tracking</h2>
	<hr>',
			),
			array (
				'key' => 'field_53c67f29a9974',
				'label' => 'RFI Number',
				'name' => 'rfi_number',
				'type' => 'number',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			/*
			array (
				'key' => 'field_53c67fe0a9975',
				'label' => 'Status',
				'name' => 'status',
				'type' => 'taxonomy',
				'taxonomy' => 'em_status',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 0,
				'return_format' => 'object',
				'multiple' => 0,
			),
			array (
				'key' => 'field_53c67fffa9976',
				'label' => 'Date Generated',
				'name' => 'date_generated',
				'type' => 'date_picker',
				'required' => 1,
				'date_format' => 'yymmdd',
				'display_format' => 'mm/dd/yy',
				'first_day' => 1,
			),
			*/
			array (
				'key' => 'field_53c68020a9977',
				'label' => 'Date Due',
				'name' => 'date_due',
				'type' => 'date_picker',
				'required' => 1,
				'date_format' => 'yymmdd',
				'display_format' => 'mm/dd/yy',
				'first_day' => 1,
			),
			/*
			array (
				'key' => 'field_53c68137a9979',
				'label' => 'Generated by',
				'name' => 'generated_by',
				'type' => 'user',
				'required' => 1,
				'role' => array (
					0 => 'all',
				),
				'field_type' => 'select',
				'allow_null' => 0,
			),
			array (
				'key' => 'field_53c68148a997a',
				'label' => 'Assigned to',
				'name' => 'assigned_to',
				'type' => 'user',
				'required' => 1,
				'role' => array (
					0 => 'all',
				),
				'field_type' => 'select',
				'allow_null' => 0,
			),
			*/
			array (
				'key' => 'field_53c6815da997b',
				'label' => 'Question',
				'name' => 'question',
				'type' => 'message',
				'message' => '<h2>Question</h2>
	<hr>',
			),
			array (
				'key' => 'field_53c7e47e6b1ee',
				'label' => 'CSI Division',
				'name' => 'csi_division',
				'type' => 'taxonomy',
				'required' => 1,
				'taxonomy' => 'em_csidivisions',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_53c6b424aed24',
				'label' => 'Associated With',
				'name' => 'associated_with',
				'type' => 'checkbox',
				'choices' => array (
					'Location' => 'Location',
					'Drawing Number' => 'Drawing Number',
					'Specification' => 'Specification',
				),
				'default_value' => 'Location',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_53c6b44caed25',
				'label' => 'Location',
				'name' => 'scope',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_53c6b424aed4a',
						'label' => $tier1,
						'name' => 'building',
						'type' => 'select',
						'column_width' => '15',
						'choices' => array (
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_53c6b424aed4b',
						'label' => $tier2,
						'name' => 'floor',
						'type' => 'select',
						'column_width' => '15',
						'choices' => array (
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_53c6b424aed4c',
						'label' => $tier3,
						'name' => 'location',
						'type' => 'select',
						'column_width' => '15',
						'choices' => array (
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_53c6b424aed4d',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_53c6b4c1aed26',
				'label' => 'Drawing Number',
				'name' => 'drawing_number',
				'type' => 'repeater',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53c6b424aed24',
							'operator' => '==',
							'value' => 'Drawing Number',
						),
					),
					'allorany' => 'any',
				),
				'sub_fields' => array (
					array (
						'key' => 'field_53c6b4e4aed27',
						'label' => 'Drawing',
						'name' => 'drawing',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '1',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_53c6b4f5aed28',
				'label' => 'Specification',
				'name' => 'specification',
				'type' => 'repeater',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53c6b424aed24',
							'operator' => '==',
							'value' => 'Specification',
						),
					),
					'allorany' => 'any',
				),
				'sub_fields' => array (
					array (
						'key' => 'field_53c6b4f5aed29',
						'label' => 'Specification',
						'name' => 'specification',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '1',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_53c681a2a997d',
				'label' => 'Question',
				'name' => 'question',
				'type' => 'textarea',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_53c681bda997e',
				'label' => 'PCO Number',
				'name' => 'pco_number',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_53c681d7a997f',
				'label' => 'Schedule Impact',
				'name' => 'schedule_impact',
				'type' => 'radio',
				'required' => 1,
				'choices' => array (
					'Yes' => 'Yes',
					'No' => 'No',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'No',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_53c68201a9980',
				'label' => 'Attachment(s)',
				'name' => 'attachments',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_53c6845de1668',
						'label' => 'File',
						'name' => 'file',
						'type' => 'file',
						'column_width' => '',
						'save_format' => 'url',
						'library' => 'uploadedTo',
					),
				),
				'row_min' => '1',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add File',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'em_rfi',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}