<?php

if ( function_exists("register_field_group") )
{
	register_field_group(array (
		'id' => 'acf_activities',
		'title' => 'Activities',
		'fields' => array (
			array (
				'key' => 'field_53b17d3954edf',
				'label' => 'Estimated Start',
				'name' => 'estimated_start',
				'type' => 'date_picker',
				'required' => 1,
				'date_format' => 'yymmdd',
				'display_format' => 'mm/dd/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_53b17d6554ee1',
				'label' => 'Estimated Duration',
				'name' => 'estimated_duration',
				'type' => 'number',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_53b17d4d54ee0',
				'label' => 'Estimated Complete',
				'name' => 'estimated_complete',
				'type' => 'date_picker',
				'date_format' => 'yymmdd',
				'display_format' => 'mm/dd/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_53b17d7a54ee2',
				'label' => 'Actual Start',
				'name' => 'actual_start',
				'type' => 'date_picker',
				'date_format' => 'yymmdd',
				'display_format' => 'mm/dd/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_53b17da554ee3',
				'label' => 'Actual Complete',
				'name' => 'actual_complete',
				'type' => 'date_picker',
				'date_format' => 'yymmdd',
				'display_format' => 'mm/dd/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_53b1c00d5cd2c',
				'label' => 'Percent Complete',
				'name' => 'percent_complete',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '%',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_53b17db554ee4',
				'label' => 'Location',
				'name' => 'location',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'em_locations',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 1,
			),
			array (
				'key' => 'field_53b1bfda5cd29',
				'label' => 'Resources',
				'name' => 'resources',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_53b1bfeb5cd2a',
						'label' => 'Type',
						'name' => 'type',
						'type' => 'post_object',
						'column_width' => '',
						'post_type' => array (
							0 => 'em_employees',
							1 => 'em_equipment',
							2 => 'em_labortypes',
							3 => 'em_materials',
						),
						'taxonomy' => array (
							0 => 'all',
						),
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_53b1c00d5cd2b',
						'label' => 'Quantity',
						'name' => 'quantity',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Resource',
			),
			array (
				'key' => 'field_53b17e5854ee6',
				'label' => 'Notes',
				'name' => 'notes',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'em_activities',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}