<?php

if ( function_exists("register_field_group") )
{
	register_field_group(array (
		'id' => 'acf_ssi',
		'title' => 'SSI',
		'fields' => array (
			array (
				'key' => 'field_53a43fc4a1446',
				'label' => 'Package Number',
				'name' => 'package_number',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53a43fd2a1447',
				'label' => 'Package Title',
				'name' => 'package_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53a43fe0a1448',
				'label' => 'Package Date',
				'name' => 'package_date',
				'type' => 'date_picker',
				'date_format' => 'yymmdd',
				'display_format' => 'mm/dd/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_53a44003a1449',
				'label' => 'Issue To',
				'name' => 'issue_to',
				'type' => 'user',
				'role' => array (
					0 => 'owner',
					1 => 'owners_rep',
				),
				'field_type' => 'select',
				'allow_null' => 0,
			),
			array (
				'key' => 'field_53a4401aa144a',
				'label' => 'Importance',
				'name' => 'importance',
				'type' => 'select',
				'choices' => array (
					'Low' => 'Low',
					'Medium' => 'Medium',
					'High' => 'High',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_53a44050a144b',
				'label' => 'Status',
				'name' => 'status',
				'type' => 'taxonomy',
				'taxonomy' => 'em_status',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_53a44063a144c',
				'label' => 'Write Up',
				'name' => 'write_up',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_53a44095a144d',
				'label' => 'Document List',
				'name' => 'document_list',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_53a440b1a144e',
						'label' => 'Document Number',
						'name' => 'document_number',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_53a440c3a144f',
						'label' => 'Revision Number',
						'name' => 'revision_number',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_53a440e8a1450',
						'label' => 'Document Title',
						'name' => 'document_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53a440faa1451',
						'label' => 'File',
						'name' => 'file',
						'type' => 'file',
						'column_width' => '',
						'save_format' => 'object',
						'library' => 'uploadedTo',
					),
					array (
						'key' => 'field_53a44106a1452',
						'label' => 'Notes',
						'name' => 'notes',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_53a44122a1453',
				'label' => 'sign_confirm',
				'name' => '',
				'type' => 'message',
				'message' => 'Sign & Confirm',
			),
			array (
				'key' => 'field_53a44143a1454',
				'label' => 'Signature',
				'name' => 'signature',
				'type' => 'signature',
				'required' => 0,#(is_admin() ? 0 : 1),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'em_ssi',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}