<?php

if ( function_exists("register_field_group") )
{
    if ( ! ($tier1 = get_option('options_location_tier_1')) ) {
        $tier1 = 'Building';
    }
    if ( ! ($tier2 = get_option('options_location_tier_2')) ) {
        $tier2 = 'Floor';
    }
    if ( ! ($tier3 = get_option('options_location_tier_3')) ) {
        $tier3 = 'Subarea';
    }

	register_field_group(array (
		'id' => 'acf_options-license-key',
		'title' => 'Options: License Key',
		'fields' => array (
/** /
			array (
				'key' => 'field_52f7f944e6e83',
				'label' => 'eManager License Key',
				'name' => 'edd_emanager_license_key',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
/**/
			array (
				'key' => 'field_52f7f944e6e84',
				'label' => 'Wunderground API Key',
				'name' => 'wunderground_api_key',
				'type' => 'text',
				'default_value' => '06e499c7b392f4b5',
				'placeholder' => '',
				'prepend' => '',
				'append' => 'Key can be registered at <a href="http://www.wunderground.com/weather/api/" target="_blank">Wundergound</a>',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-license-key',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 2005,
	));

	register_field_group(array (
		'id' => 'acf_options-job-info',
		'title' => 'Options: Job Info',
		'fields' => array (
			array (
				'key' => 'field_52a5312827fbe',
				'label' => 'Project Name',
				'name' => 'proj_name',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52a5313e27fbf',
				'label' => 'Project Street Address',
				'name' => 'proj_address',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52a5315327fc0',
				'label' => 'Project City',
				'name' => 'proj_city',
				'type' => 'text',
				'default_value' => 'New York',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52a5315327fc5',
				'label' => 'Project City State',
				'name' => 'proj_state',
				'type' => 'select',
				'choices' => array (
                    'AL'=>'Alabama',
		            'AK'=>'Alaska',
		            'AZ'=>'Arizona',
		            'AR'=>'Arkansas',
		            'CA'=>'California',
		            'CO'=>'Colorado',
		            'CT'=>'Connecticut',
		            'DE'=>'Delaware',
		            'DC'=>'District Of Columbia',
		            'FL'=>'Florida',
		            'GA'=>'Georgia',
		            'HI'=>'Hawaii',
		            'ID'=>'Idaho',
		            'IL'=>'Illinois',
		            'IN'=>'Indiana',
		            'IA'=>'Iowa',
		            'KS'=>'Kansas',
		            'KY'=>'Kentucky',
		            'LA'=>'Louisiana',
		            'ME'=>'Maine',
		            'MD'=>'Maryland',
		            'MA'=>'Massachusetts',
		            'MI'=>'Michigan',
		            'MN'=>'Minnesota',
		            'MS'=>'Mississippi',
		            'MO'=>'Missouri',
		            'MT'=>'Montana',
		            'NE'=>'Nebraska',
		            'NV'=>'Nevada',
		            'NH'=>'New Hampshire',
		            'NJ'=>'New Jersey',
		            'NM'=>'New Mexico',
		            'NY'=>'New York',
		            'NC'=>'North Carolina',
		            'ND'=>'North Dakota',
		            'OH'=>'Ohio',
		            'OK'=>'Oklahoma',
		            'OR'=>'Oregon',
		            'PA'=>'Pennsylvania',
		            'RI'=>'Rhode Island',
		            'SC'=>'South Carolina',
		            'SD'=>'South Dakota',
		            'TN'=>'Tennessee',
		            'TX'=>'Texas',
		            'UT'=>'Utah',
		            'VT'=>'Vermont',
		            'VA'=>'Virginia',
		            'WA'=>'Washington',
		            'WV'=>'West Virginia',
		            'WI'=>'Wisconsin',
		            'WY'=>'Wyoming',
					'INT'=>'International'
                ),
				'default_value' => 'NY',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_52a5316627fc1',
				'label' => 'Project Zip Code',
				'name' => 'proj_zipcode',
				'type' => 'text',
				'default_value' => 10001,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52a5318427fc2',
				'label' => 'Project Phone',
				'name' => 'proj_phone',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52a5319127fc3',
				'label' => 'Project Fax',
				'name' => 'proj_fax',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52a531a327fc4',
				'label' => 'Start Date',
				'name' => 'proj_start',
				'type' => 'date_picker',
				'date_format' => 'yymmdd',
				'display_format' => 'mm/dd/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_52a531eff46ad',
				'label' => 'Business Unit',
				'name' => 'business_unit',
				'type' => 'select',
				'choices' => array (
                    'boston' => 'Boston',
                    'connecticut' => 'Connecticut',
                    'denver' => 'Denver',
                    'great_lakes' => 'Great Lakes',
                    'international' => 'International',
                    'kansas_city' => 'Kansas City',
                    'maryland' => 'Maryland',
                    'midatlantic' => 'Mid-Atlantic',
                    'new_jersey' => 'New Jersey',
                    'new_york' => 'New York',
                    'ohio' => 'Ohio',
                    'pennsylvania' => 'Pennsylvania',
                    'portland' => 'Portland',
                    'seattle' => 'Seattle',
                    'southeast' => 'Southeast',
                    'southwestnocal' => 'Southwest and NoCal',
                    'texas' => 'Texas'
                ),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_52a531f9f46ae',
				'label' => 'Type of Contract',
				'name' => 'contract_type',
				'type' => 'select',
				'choices' => array (
					'Cost Plus' => 'Cost Plus',
					'Lump Sum' => 'Lump Sum',
					'GMP' => 'GMP',
					'Other' => 'Other',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_52a5321c0c736',
				'label' => 'Contract Number',
				'name' => 'contract_number',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_52a532280c737',
				'label' => 'Type of Construction',
				'name' => 'construction_type',
				'type' => 'select',
				'choices' => array (
					'Base Building' => 'Base Building',
					'Renovation' => 'Renovation',
					'Addition' => 'Addition',
					'Other' => 'Other',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_52a532c0f0e0f',
				'label' => 'Type of Building',
				'name' => 'building_type',
				'type' => 'select',
				'choices' => array (
					'Commercial' => 'Commercial',
					'Residential' => 'Residential',
					'Healthcare' => 'Healthcare',
					'Other' => 'Other',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_52a532eef0e10',
				'label' => 'Company ID',
				'name' => 'company_id',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_52a532f8f0e11',
				'label' => 'Project ID',
				'name' => 'project_id',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_52a532fff0e12',
				'label' => 'Contract Value',
				'name' => 'contract_value',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52a5330cf0e13',
				'label' => 'Phase of Project',
				'name' => 'phase_of_project',
				'type' => 'select',
				'choices' => array (
					'Preconstruction' => 'Preconstruction',
					'Construction' => 'Construction',
					'Facilities Management' => 'Facilities Management',
					'Other' => 'Other',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_52a5333ff0e14',
				'label' => 'Approval Threshold',
				'name' => 'approval_threshold',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-job-info',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 2010,
	));

	register_field_group(array (
		'id' => 'acf_options-site-settings',
		'title' => 'Options: Site Settings',
		'fields' => array (
			array (
				'key' => 'field_52aec6bea764c',
				'label' => 'Currency',
				'name' => 'currency',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			/*
			// Deprecated; no need to integrate drobox when we have elfinder
			array (
				'key' => 'field_52aec693a764b',
				'label' => 'Dropbox Base Folder',
				'name' => 'dropbox_base_folder',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			*/
			/*
            // Add future field for records per table view / search page #request by @mlamm
			// use something like $posts_per_page = eman_get_field('em_posts_per_page', 'option');
			*/
			array (
				'key' => 'field_52aec694a769c',
				'label' => 'Records per table view page',
				'name' => 'em_posts_per_page',
				'type' => 'number',
				'default_value' => '25',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52aec6e5a764d',
				'label' => 'RSS URL',
				'name' => 'rss_url',
				'type' => 'text',
				'default_value' => 'https://www.facebook.com/feeds/page.php?id=363996093623367&format=rss20',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52aec711a764e',
				'label' => 'Welcome Title',
				'name' => 'welcome_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52aec720a764f',
				'label' => 'Welcome Content',
				'name' => 'welcome_content',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_52aec72fa7650',
				'label' => 'Pending Title',
				'name' => 'pending_title',
				'type' => 'text',
				'default_value' => 'Your Account is Pending',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52aec73da7651',
				'label' => 'Pending Content',
				'name' => 'pending_content',
				'type' => 'textarea',
				'default_value' => 'Your account is still awaiting review and confirmation. It should be activated soon, but if you are having problems, please contact an administrator.',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5432fd214cmc8',
				'label' => 'Advanced PDF Viewer',
				'name' => 'pdf_advanced',
				'type' => 'radio',
				'choices' => array (
					'Yes' => 'Yes',
					'No' => 'No',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'Yes',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_52eda66db8395',
				'label' => 'SAP Reasons',
				'name' => 'sap_reasons',
				'type' => 'checkbox',
				'instructions' => 'Uncheck reasons that shouldn not be available for this job.',
				'choices' => array (
					'Allowance' => 'Allowance',
					'Back Charge' => 'Back Charge',
					'Change Condition' => 'Change Condition',
					'Change in Terms & Conditions' => 'Change in Terms & Conditions',
					'Claim' => 'Claim',
					'Code / Regulatory' => 'Code / Regulatory',
					'Consultant Directive' => 'Consultant Directive',
					'Contingency' => 'Contingency',
					'Design Issue' => 'Design Issue',
					'Direct Costs' => 'Direct Costs',
					'Expedite / OT' => 'Expedite / OT',
					'Extend GCs' => 'Extend GCs',
					'GC/GR' => 'GC/GR',
					'Inspection Result' => 'Inspection Result',
					'Owner Directive' => 'Owner Directive',
					'Strike' => 'Strike',
					'Transfer' => 'Transfer',
					'Unbought' => 'Unbought',
					'Unforseen Conditions' => 'Unforseen Conditions',
				),
				'default_value' => 'Allowance
				Back Charge
				Change Condition
				Change in Terms & Conditions
				Claim
				Code / Regulatory
				Consultant Directive
				Contingency
				Design Issue
				Direct Costs
				Expedite / OT
				Extend GCs
				GC/GR
				Inspection Result
				Owner Directive
				Strike
				Transfer
				Unbought
				Unforseen Conditions',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_52a09u23rnjo3',
				'label' => 'DCR Labor Breakdown',
				'name' => 'dcr_labor_breakdown',
				'type' => 'select',
				'choices' => array (
					'Man-days' => 'Man-days',
					'Man-hours' => 'Man-hours',
				),
				'default_value' => 'Man-days',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_27163f791dcb9',
				'label' => 'Location Tier 1',
				'name' => 'location_tier_1',
				'type' => 'text',
				'default_value' => 'Building',
				'placeholder' => $tier1,
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_70ceca4d13acd',
				'label' => 'Location Tier 2',
				'name' => 'location_tier_2',
				'type' => 'text',
				'default_value' => 'Floor',
				'placeholder' => $tier2,
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_60567cff52262',
				'label' => 'Location Tier 3',
				'name' => 'location_tier_3',
				'type' => 'text',
				'default_value' => 'Subarea',
				'placeholder' => $tier3,
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5432fd214cda8',
				'label' => 'Additional Direction',
				'name' => 'additional_direction',
				'type' => 'radio',
				'choices' => array (
					'Yes' => 'Yes',
					'No' => 'No',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'No',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_5432fd414cda9',
				'label' => 'Direction(s)',
				'name' => 'direction_list',
				'type' => 'repeater',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5432fd214cda8',
							'operator' => '==',
							'value' => 'Yes',
						),
					),
					'allorany' => 'all',
				),
				'sub_fields' => array (
					array (
						'key' => 'field_5432fd6c4cdaa',
						'label' => 'Direction',
						'name' => 'direction',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-site-settings',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 2020,
	));

	$field_group = array (
		'id' => 'acf_options-staff-assignments',
		'title' => 'Options: Staff Assignments',
		'fields' => array (
			array (
				'key' => 'field_52aec77a58409',
				'label' => 'Ticket Authorizers',
				'name' => 'ticket_approvers',
				'type' => 'user',
				'role' => array (
					0 => 'administrator',
					1 => 'editor',
				),
				'field_type' => 'multi_select',
				'allow_null' => 0,
			),
			array (
				'key' => 'field_52aec79b5840a',
				'label' => 'PCO Authorizers',
				'name' => 'pco_approvers',
				'type' => 'user',
				'role' => array (
					0 => 'administrator',
					1 => 'editor',
				),
				'field_type' => 'multi_select',
				'allow_null' => 0,
			),
			array (
				'key' => 'field_52aec7b15840b',
				'label' => 'NOC Gatekeeper',
				'name' => 'noc_gatekeeper',
				'type' => 'user',
				'role' => array (
					0 => 'administrator',
					1 => 'editor',
				),
				'field_type' => 'multi_select',
				'allow_null' => 0,
			),
			array (
				'key' => 'field_52aec7c85840c',
				'label' => 'DCR Reviewers',
				'name' => 'dcr_reviewers',
				'type' => 'user',
				'role' => array (
					0 => 'administrator',
					1 => 'editor',
				),
				'field_type' => 'multi_select',
				'allow_null' => 0,
			),
			array (
				'key' => 'field_536692bccaa2d',
				'label' => 'Incident Notification',
				'name' => 'incident_notification',
				'type' => 'user',
				'role' => array (
					0 => 'administrator',
					1 => 'editor',
				),
				'field_type' => 'multi_select',
				'allow_null' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-staff-assignments',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 2030,
	);

	register_field_group( apply_filters( 'eman/field_groups/options-staff-assignments', $field_group ) );
}