<?php

if ( function_exists("register_field_group") )
{
	register_field_group(array (
		'id' => 'acf_letter',
		'title' => 'Letters',
		'fields' => array (
			array (
				'key' => 'field_54622b5dfe5c6',
				'label' => 'Type',
				'name' => 'letter_type',
				'type' => 'radio',
				'choices' => array (
					'AL' => 'AL',
					'COR' => 'COR',
					'NOC' => 'NOC',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'required' => (is_admin() ? 0 : 1),
			),
			array (
				'key' => 'field_54622b98fe5c7',
				'label' => 'Corresponding Number',
				'name' => 'letter_number',
				'type' => 'number',
				'required' => (is_admin() ? 0 : 1),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '#',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_54622c41fe5c8',
				'label' => 'Date',
				'name' => 'date',
				'type' => 'date_picker',
				'required' => (is_admin() ? 0 : 1),
				'date_format' => 'yymmdd',
				'display_format' => 'mm/dd/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_5465028cca859',
				'label' => 'Revision #',
				'name' => 'revision',
				'type' => 'number',
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '#',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_54622ea6a219f',
				'label' => 'PCO Number',
				'name' => 'pco_number',
				'type' => 'number',
				'required' => (is_admin() ? 0 : 1),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '#',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_54622contractornum',
				'label' => 'Contractor Number',
				'name' => 'sub_number',
				'type' => 'number',
				'required' => 0,#(is_admin() ? 0 : 1),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '#',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
/** /
			array (
				'key' => 'field_54622ea6a218g',
				'label' => 'NOC Number',
				'name' => 'noc_number',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '#',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
/**/
			array (
				'key' => 'field_54622ec5a21a0',
				'label' => 'Description',
				'name' => 'description',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_54622c91fe5c9',
				'label' => 'Itemized',
				'name' => 'itemized',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_54622ca3fe5ca',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'text',
						'column_width' => 40,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_54622cb8fe5cb',
						'label' => 'Amount Proposed',
						'name' => 'amount_proposed',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '$',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_54622cc4fe5cc',
						'label' => 'Contract',
						'name' => 'contract',
						'type' => 'post_object',
						'column_width' => '',
						'post_type' => array (
							0 => 'em_contracts',
						),
						'taxonomy' => array (
							0 => 'all',
						),
						'allow_null' => 0,
						'multiple' => 0,
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Item',
			),
			array (
				'key' => 'field_54622cd6fe5cd',
				'label' => 'Funding',
				'name' => 'funding',
				'type' => 'repeater',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_54622b5dfe5c6',
							'operator' => '==',
							'value' => 'AL',
						),
					),
					'allorany' => 'all',
				),
				'sub_fields' => array (
					array (
						'key' => 'field_54650258ca858',
						'label' => 'Funding Source',
						'name' => 'funding_source',
						'type' => 'post_object',
						'column_width' => '',
						'post_type' => array (
							0 => 'em_funding',
						),
						'taxonomy' => array (
							0 => 'all',
						),
						'allow_null' => 0,
						'multiple' => 0,
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Source',
			),
			array (
				'key' => 'field_54622ea6a22e45',
				'label' => 'Total Value',
				'name' => 'value',
				'type' => 'number',
				'required' => (is_admin() ? 0 : 1),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '$',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			/* Not interested in this just yet *//*
			array (
				'key' => 'field_54622d0efe5ce',
				'label' => 'Sections',
				'name' => 'sections',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_54622d1afe5cf',
						'label' => 'Section',
						'name' => 'section',
						'type' => 'textarea',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'formatting' => 'br',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
			*/
			array (
				'key' => 'field_54622d27fe5d0',
				'label' => 'Backup',
				'name' => 'backup',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_54622d30fe5d1',
						'label' => 'File',
						'name' => 'file',
						'type' => 'file',
						'column_width' => '',
						'save_format' => 'url',
						'library' => 'all',
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_52b00d98dfa',
				'label' => 'Send To',
				'name' => 'turner_responsible',
				'type' => 'user',
				'required' => (is_admin() ? 0 : 1),
				'role' => array (
					0 => 'administrator',
					1 => 'editor',
					2 => 'owners_rep',
					3 => 'consultant',
					4 => 'owner',
				),
				'field_type' => 'select',
				'allow_null' => 1,
			),
			array (
				'key' => 'field_52b00dc4c2e78',
				'label' => 'Signature',
				'name' => 'signature',
				'type' => 'signature',
				'required' => 0,#(is_admin() ? 0 : 1),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'em_letter',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));

	register_field_group(array (
		'id' => 'bic_letter_submit',
		'title' => 'Letter Submit: Change Status',
		'fields' => array (
			array (
				'key' => 'field_53a44taxstatus',
				'label' => 'Status',
				'name' => 'status',
				'type' => 'taxonomy',
				'taxonomy' => 'em_status',
				'field_type' => 'select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
				'required' => (is_admin() ? 0 : 1),
			),
			array (
				'key' => 'field_52b026eletterbic',
				'label' => 'Change Ball In Court (BIC) To',
				'name' => 'send_to',
				'type' => 'user',
				'required' => (is_admin() ? 0 : 1),
				'role' => array (
					0 => 'administrator',
					1 => 'editor',
					2 => 'owners_rep',
					3 => 'consultant',
					4 => 'owner',
				),
				'field_type' => 'select',
				'allow_null' => 1,
			),
			array (
				'key' => 'field_52b00dc4c2e782',
				'label' => 'Signature',
				'name' => 'signature',
				'type' => 'signature',
				'required' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'em_review',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}