<?php

if ( function_exists("register_field_group") )
{
	register_field_group(array (
		'id' => 'acf_labortypes',
		'title' => 'Labor Types',
		'fields' => array (
			array (
				'key' => 'field_52a72bc16c3bd',
				'label' => 'Company',
				'name' => 'company',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'em_companies',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),

			array (
				'key' => 'field_valid_from',
				'label' => 'Valid from',
				'name' => 'validfrom',
                'type' => 'date_picker',
                'date_format' => 'yymmdd',
                'display_format' => 'mm/dd/yy',
                'first_day' => 1,
			),
			array (
				'key' => 'field_valid_to',
				'label' => 'Valid to',
				'name' => 'validto',
                'type' => 'date_picker',
                'date_format' => 'yymmdd',
                'display_format' => 'mm/dd/yy',
                'first_day' => 1,
			),
			array (
                'key' => 'field_active',
                'label' => 'Active',
                'name' => 'active_labortype',
                'type' => 'select',
                'choices' => array (
                    '1' => 'Active',
                    '-1' => 'Inactive',
                ),
                'default_value' => '1',
                'allow_null' => 0,
                'multiple' => 0,
            ),

			array (
				'key' => 'field_529fcc14d3598',
				'label' => 'Regular Time Rate',
				'name' => 'rt',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_529fcc2ed3599',
				'label' => 'Premium Time Rate',
				'name' => 'pt',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_529fcc69d359a',
				'label' => 'Overtime Rate',
				'name' => 'ot',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_529fcc9dd359b',
				'label' => 'Double Time Rate',
				'name' => 'dt',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_529fccbfd359c',
				'label' => 'Premium Double Time Rate',
				'name' => 'pdt',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_529fccbfd359d',
				'label' => 'Labor Rate Sheet',
				'name' => 'ratesheet_labor',
				'type' => 'file',
				'instructions' => 'Upload PDF',
				'save_format' => 'url',
				'library' => 'uploadedTo',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'em_labortypes',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
