<?php

if ( function_exists("register_field_group") )
{
	register_field_group(array (
		'id' => 'acf_contracts',
		'title' => 'Contracts',
		'fields' => array (
			array (
				'key' => 'field_52a551396dcf0',
				'label' => 'Contract #',
				'name' => 'number',
				'type' => 'number',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_52a551776dcf1',
				'label' => 'Company Name',
				'name' => 'company',
				'type' => 'post_object',
				'required' => 1,
				'post_type' => array (
					0 => 'em_companies',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_52a551b06dcf2',
				'label' => 'Vendor #',
				'name' => 'vendor',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52a551d16dcf3',
				'label' => 'Purchase Order #',
				'name' => 'purchase',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52a551ed6dcf4',
				'label' => 'Bid Package #',
				'name' => 'bid_number',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52a5521d6dcf5',
				'label' => 'Bid Package Title',
				'name' => 'bid_description',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52a552476dcf6',
				'label' => 'WBS #',
				'name' => 'wbs',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52a552476dcf8',
				'label' => 'Value',
				'name' => 'contract_value',
				'type' => 'number',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_52a552636dcf7',
				'label' => 'CSI',
				'name' => 'csi',
				'type' => 'taxonomy',
				//'required' => 1,
				'taxonomy' => 'em_csidivisions',
				'field_type' => 'select',
				'allow_null' => 1,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			)
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'em_contracts',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}