<?php

if ( function_exists("register_field_group") )
{
    if ( ! ($tier1 = get_option('options_location_tier_1')) ) {
        $tier1 = 'Building';
    }
    if ( ! ($tier2 = get_option('options_location_tier_2')) ) {
        $tier2 = 'Floor';
    }
    if ( ! ($tier3 = get_option('options_location_tier_3')) ) {
        $tier3 = 'Subarea';
    }

	register_field_group(array (
		'id' => 'acf_tickets',
		'title' => 'Tickets',
		'fields' => array (
			array (
				'key' => 'field_52b84aticket',
				'label' => 'Company',
				'name' => 'company',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'em_companies',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 0,
				'required' => (is_admin() ? 0 : 1),
			),
			array (
				'key' => 'field_52affd3cad640',
				'label' => 'Authorized PCO#',
				'name' => 'pco_number',
				'type' => 'number',
				'required' => (is_admin() ? 0 : 1),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_52affd73ad641',
				'label' => 'Sub EWO# (if applicable)',
				'name' => 'ewo_number',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52affd91ad642',
				'label' => 'Work Date',
				'name' => 'work_date',
				'type' => 'date_picker',
				'date_format' => 'yymmdd',
				'display_format' => 'mm/dd/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_52affdb0ad643',
				'label' => 'Shift',
				'name' => 'shift',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52affdcdad644',
				'label' => 'Last Ticket of Series',
				'name' => 'last_ticket',
				'type' => 'radio',
				'choices' => array (
					'Yes' => 'Yes',
					'No' => 'No',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'No',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_52eac0ticketscope',
				'label' => 'Scope',
				'name' => 'scope',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_52eac327b9c2e',
						'label' => $tier1,
						'name' => 'building',
						'type' => 'select',
						'column_width' => '15',
						'choices' => array (
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_52eac405b9c2f',
						'label' => $tier2,
						'name' => 'floor',
						'type' => 'select',
						'column_width' => '15',
						'choices' => array (
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_52eac4c7b9c30',
						'label' => 'Location',
						'name' => 'location',
						'type' => 'select',
						'column_width' => '15',
						'choices' => array (
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_52eac4e0b9c31',
						'label' => 'Scope',
						'name' => 'scope',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_52b00338ad647',
				'label' => 'Description',
				'name' => 'description',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_52b0034ead648',
				'label' => 'Backup',
				'name' => 'backup',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_529f5da2f850a',
						'label' => 'File',
						'name' => 'file',
						'type' => 'file',
						'column_width' => '',
						'save_format' => 'url',
						'library' => 'uploadedTo',
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add File',
			),
			array (
				'key' => 'field_52b0036ead649',
				'label' => 'Labor',
				'name' => '',
				'type' => 'message',
				'message' => '<hr class="divider divider-before" />
	<h2>Labor</h2>
	<hr class="divider divider-after" />',
			),
			array (
				'key' => 'field_52b0038fad64a',
				'label' => 'Labor Breakdown',
				'name' => 'laborbd',
				'type' => 'radio',
				'choices' => array (
					'classification' => 'By Labor Classification',
					'employee' => 'By Employee Name',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'classification',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_52b003eead64b',
				'label' => 'Employee Breakdown',
				'name' => 'employee_breakdown',
				'type' => 'repeater',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_52b0038fad64a',
							'operator' => '==',
							'value' => 'employee',
						),
					),
					'allorany' => 'all',
				),
				'sub_fields' => array (
					array (
						'key' => 'field_52b0045382f59',
						'label' => 'Employee',
						'name' => 'employee',
						'type' => 'post_object',
						'column_width' => 25,
						'post_type' => array (
							0 => 'em_employees',
						),
						'taxonomy' => array (
							0 => 'all',
						),
						'allow_null' => 1,
						'multiple' => 0,
					),
					array (
						'key' => 'field_52b0048082f5a',
						'label' => 'RT',
						'name' => 'rt',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'hrs',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_52b004a382f5b',
						'label' => 'OT',
						'name' => 'ot',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'hrs',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_52b004b682f5c',
						'label' => 'DT',
						'name' => 'dt',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'hrs',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_52b004d582f5d',
						'label' => 'PT',
						'name' => 'pt',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'hrs',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_52b004f482f5e',
						'label' => 'PDT',
						'name' => 'pdt',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'hrs',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_544695271c135',
						'label' => 'Scope No',
						'name' => 'scope_no',
						'type' => 'number',
						'column_width' => 5,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Employee',
			),
			array (
				'key' => 'field_52b0050a82f5f',
				'label' => 'Classification Breakdown',
				'name' => 'classification_breakdown',
				'type' => 'repeater',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_52b0038fad64a',
							'operator' => '==',
							'value' => 'classification',
						),
					),
					'allorany' => 'all',
				),
				'sub_fields' => array (
					array (
						'key' => 'field_52b0052282f60',
						'label' => 'Type',
						'name' => 'type',
						'type' => 'post_object',
						'column_width' => 30,
						'post_type' => array (
							0 => 'em_labortypes',
						),
						'taxonomy' => array (
							0 => 'all',
						),
						'allow_null' => 1,
						'multiple' => 0,
					),
					array (
						'key' => 'field_52b0055082f61',
						'label' => 'Count',
						'name' => 'count',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_52b0056e82f62',
						'label' => 'RT',
						'name' => 'rt',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'hrs',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_52b0059082f63',
						'label' => 'OT',
						'name' => 'ot',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'hrs',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_52b0059e82f64',
						'label' => 'DT',
						'name' => 'dt',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'hrs',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_52b005b682f65',
						'label' => 'PT',
						'name' => 'pt',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'hrs',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_52b005db82f66',
						'label' => 'PDT',
						'name' => 'pdt',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'hrs',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_544695271c135',
						'label' => 'Scope No',
						'name' => 'scope_no',
						'type' => 'number',
						'column_width' => 5,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Labor Type',
			),
			array (
				'key' => 'field_52b0061504e25',
				'label' => 'Labor Markup',
				'name' => 'labor_markup',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_52b0062c04e26',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'additional' => 'Additional Markup',
							'overhead' => 'Overhead',
							'profit' => 'Profit',
							'tax' => 'Tax',
							'insurance' => 'Insurance',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_52b007a304e27',
						'label' => 'Value (%)',
						'name' => 'value',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '%',
						'min' => '',
						'max' => '',
						'step' => '',
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Markup',
			),
			array (
				'key' => 'field_52b007cb04e28',
				'label' => 'Material Breakdown',
				'name' => '',
				'type' => 'message',
				'message' => '<hr class="divider divider-before" />
	<h2>Material</h2>
	<hr class="divider divider-after" />',
			),
			array (
				'key' => 'field_52b007f204e29',
				'label' => 'Materials',
				'name' => 'materials',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_52b0080b04e2a',
						'label' => 'Name',
						'name' => 'name',
						'type' => 'post_object',
						'column_width' => 30,
						'post_type' => array (
							0 => 'em_materials',
						),
						'taxonomy' => array (
							0 => 'all',
						),
						'allow_null' => 1,
						'multiple' => 0,
					),
					array (
						'key' => 'field_52b00995de834',
						'label' => 'Unit of Measure',
						'name' => 'measure',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_52b00995de833',
						'label' => 'Rate (per Unit of Measure)',
						'name' => 'price',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '$',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_52b00962de832',
						'label' => 'Amount Used',
						'name' => 'amount_used',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_544695271c135',
						'label' => 'Scope No',
						'name' => 'scope_no',
						'type' => 'number',
						'column_width' => 5,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Material',
			),
			array (
				'key' => 'field_52b009d0de834',
				'label' => 'Material Markup',
				'name' => 'material_markup',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_52b009ecde835',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'additional' => 'Additional Markup',
							'overhead' => 'Overhead',
							'profit' => 'Profit',
							'tax' => 'Tax',
							'insurance' => 'Insurance',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_52b00a0ede836',
						'label' => 'Value (%)',
						'name' => 'value',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '%',
						'min' => '',
						'max' => '',
						'step' => '',
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Markup',
			),
			array (
				'key' => 'field_52b00a49de837',
				'label' => 'Equipment Breakdown',
				'name' => '',
				'type' => 'message',
				'message' => '<hr class="divider divider-before" />
	<h2>Equipment</h2>
	<hr class="divider divider-after" />',
			),
			array (
				'key' => 'field_52b00a69de838',
				'label' => 'Equipment',
				'name' => 'equipment',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_52b00a85de839',
						'label' => 'Name',
						'name' => 'name',
						'type' => 'post_object',
						'column_width' => 30,
						'post_type' => array (
							0 => 'em_equipment',
						),
						'taxonomy' => array (
							0 => 'all',
						),
						'allow_null' => 1,
						'multiple' => 0,
					),
					array (
						'key' => 'field_52b00ae7de83c',
						'label' => 'Unit of Measure',
						'name' => 'measure',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_52b00abfde83a',
						'label' => 'Rate (per Unit of Measure)',
						'name' => 'rental_price',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '$',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_52b00ae7de83b',
						'label' => 'Amount Used',
						'name' => 'usage',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_544695271c135',
						'label' => 'Scope No',
						'name' => 'scope_no',
						'type' => 'number',
						'column_width' => 5,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Equipment',
			),
			array (
				'key' => 'field_52b00b2fde83c',
				'label' => 'Equipment Markup',
				'name' => 'equipment_markup',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_52b00b98de83d',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'additional' => 'Additional Markup',
							'overhead' => 'Overhead',
							'profit' => 'Profit',
							'tax' => 'Tax',
							'insurance' => 'Insurance',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_52b00bc9de83e',
						'label' => 'Value (%)',
						'name' => 'value',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '%',
						'min' => '',
						'max' => '',
						'step' => '',
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Markup',
			),
			array (
				'key' => 'field_52b00c05de840',
				'label' => 'Global Markup',
				'name' => 'global_markup',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_52b00c1ade841',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'additional' => 'Additional Markup',
							'overhead' => 'Overhead',
							'profit' => 'Profit',
							'tax' => 'Tax',
							'insurance' => 'Insurance',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_52b00c3ede842',
						'label' => 'Value (%)',
						'name' => 'value',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '%',
						'min' => '',
						'max' => '',
						'step' => '',
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Markup',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'em_tickets',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 1020,
	));

	register_field_group(array (
		'id' => 'acf_tickets-signature',
		'title' => 'Tickets Signature',
		'fields' => array (
			array (
				'key' => 'field_52b00d8dc2e76',
				'label' => 'Divider',
				'name' => '',
				'type' => 'message',
				'message' => '<hr class="divider divider-before" />',
			),
			array (
				'key' => 'field_52b00da6c2e77',
				'label' => 'Responsible Person',
				'name' => 'turner_responsible',
				'type' => 'select',
				'choices' => array (
				),
				'default_value' => '',
				'allow_null' => 1,
				'multiple' => 0,
				'required' => (is_admin() ? 0 : 1),
			),
/** /
			array (
				'key' => 'field_52b00da6c2e77',
				'label' => 'Responsible Person',
				'name' => 'turner_responsible',
				'type' => 'user',
				'required' => (is_admin() ? 0 : 1),
				'role' => array (
					0 => 'editor',
					1 => 'administrator',
				),
				'field_type' => 'select',
				'allow_null' => 1,
			),
/**/
			array (
				'key' => 'field_52b00dc4c2e78',
				'label' => 'Signature',
				'name' => 'signature',
				'type' => 'signature',
				'required' => 0,#(is_admin() ? 0 : 1),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'em_tickets2',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 1025,
	));
}